version: '3.9'

services:
  db:
    image: postgres:16
    container_name: mma-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: mma-api
    command: pnpm run start:dev
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    ports:
      - "3000:3000"

volumes:
  postgres_data:
